services:
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
  backend:
    build: .
    container_name: backendforfastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
